env:
  global:
    - secure: "aHD0SfWYSEAavQkfMT96vIsgU1e6dR3Xg+TJrhCXE5HW2sw08udUMnLHb1BSWnUgbqArltvTnT+CEZOLqbQkuaq/VK2sW0WeQ1FarfD8ZmaA6vPO6grqKDXndWZNrRm/k3gfTHzib0PDstaQhaxBvW+thFKStxQHeAu7tLUViC5W33pIqVetB3nLDkZiwGhYbOkB76bCozt5X8/raqczHsfyCDrax8L9/kP7XJnYN5wIWwRBVaxMa/v7jfB4GYId9O7MeqeqjjbFQiDmGIBS/5OOASuoRz7i+HgVujzcEvkGfhjb5Fs0Io668Oz4VD8jRQR4I3ulvUssZ4/4ohkEbEAyheWmeboKoRyG7euiaSJtJmFtS0PtaE//YpYAVrzTKM4HdTh1uXokLKLApyJcyCNX7u1G/jScEFQQSdfdqqogs42p9YU0q4FlCsHCLqmu+/JqvslqMkcXjJsyRk/zxC/MIVi75xn14H4evj/X2qGqOiBEYjlOmzNTcvBrKL4Vv20LdGMLyOl/y1ewjW+xZGWiO1zZBikIr1pR+wru+iBhdryV9lXosO0XIPNfqM0LH3vT0SeA9ygfwQdu3zBLoZZldZKTb5CoEKxQ3tMdXNtclUABd9XaaIx/BPb62BN2qvHpZrAk9NvOfHq9rJvH9UOJVxbvsCJgUwFUpK0Ow+s="
    - secure: "nrxVgdbHJueJoiGneJjdE7l+fphcbiAzKdn79mWM88TNIrrYB9WOUFvMDzhCPXd9se8MsjGEQNs1nNyavFzH0DkvL0q1GArOoK1N9CH4Eed7SOyHZKSL5jia7Q52yvZCrohvMYYlYf+YNiKCPE34QzgNWNK+mw/+pFaeVsopcVXFyKgnclv/c957rRJaGNOaX5yG1rhTQRIn04LoiOlvYPOqla9H33TihmDVXHfMNN+NR8iKWzIKtux39XhHYCwMZHC5GIj6l0tLr5V2cURh5S/QNVDG7KOjX4qKzXKldhdoeAeP1WZSzqLlHRVdIZqQ0trLzRP+U5lNQXrBcpEZyvyaZceyh2NQwmQkkJOKcyWLN8P4XvtKkQ+7gM5/LrbVvmDxdIr/Lx7hYOdjMPEmKb+bhCcC+TKvDhTLjAL8meh5wLYq2oM4CeM7H+e1NpeRBbKdVlObKxkymcRtMZ4gNLbuaayNXLK678+MwotdoInWrQ9m3Kt/+S2O7ZIbz6zx0g4ZVvqUjqjtoFkODbcOZDr+beGCLdQJdSD7bJUFBWUfj/YQkJIEw0hrjaB+YpjB/QguruXo6cObMYM5L/sUUdrNCFM3zaTtXt9gLS0HHtb8vtwwBJVRmM4Zf3eHyQwDA4Yj/kg5kkChWUdy1oO9u9Zo0V1NXTU9CHxJIZj+uqQ="
    - COMMIT=${TRAVIS_COMMIT::8}
matrix:
    include:
        # test
        -   os: linux
            language: node_js
            node_js:
                - 8
            install:
                - yarn --version
                - yarn install
            script:
                - yarn lint
            after_success:
                - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
                    docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
                    export REPO="democracy/bundestag.io";
                    docker build -f Dockerfile -t $REPO:$COMMIT .;
                    docker tag $REPO:$COMMIT $REPO:master;
                    docker push $REPO;
                  fi
after_script:
  - echo "BUILD FINISHED"